CREATE TABLE users (
  id VARCHAR(10) PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  password VARCHAR(10) NOT NULL
);

DELETE FROM users;
ALTER TABLE users ADD level INT DEFAULT 1 NOT NULL;
ALTER TABLE users ADD login INT NOT NULL;
ALTER TABLE users ADD recommend INT NOT NULL;

ALTER TABLE users ADD email VARCHAR(100) NULL;
